### ISSUE TITLE
custom bindings do not overwrite default bindings

### ISSUE THREAD

**Issue by hunter-** [hkupty/nvimux#11]
Apologies for pestering! 

I'm now having somewhat the opposite issue — custom keybindings that are remap a key mapped to a default are overridden by the default. Eg, if I set 
`nvimux.bindings.bind_all{
     {'j', ':NvimuxHorizontalSplit', {'n', 'v', 'i', 't'}},
}`
and I call `:verbose map <C-b>j`, I see: `v  <C-Space>j  * <C-W><NL>`, not `v  <C-Space>s  * :NvimuxHorizontalSplit<CR>`

**Comment by hkupty** [comment]
I'm sorry for taking long to answer. I know what happen. Will fix ASAP.

**Comment by hkupty** [comment]
So I just merged a fix here. Should be working correctly for both the defaul and custom keys.

Thanks again for the issue. This helps nvimux to be better.

Cheers,
Henry John Kupty
