### ISSUE TITLE
open_term_by_default not working

### ISSUE THREAD

**Issue by alexanderjeurissen** [hkupty/nvimux#13]
I'm evaluating if nvimux can replace my current tmux workflow seeing as I mostly work on my local machine and rarely ssh in remote machines.

I'm stumbling across the following problem: Somehow the `open_term_by_default` option is not respected. having new splits default to terminal buffers is essential for me to use this plugin as a tmux replacement.

I tried using the following minimal neovim config:

```
packadd minpac

call minpac#init()
call minpac#add('hkupty/nvimux', { 'type': 'opt' }) 

packadd nvimux

lua << EOF
local nvimux = require('nvimux')

-- Nvimux configuration
nvimux.config.set_all{
  prefix = '<C-a>',
  open_term_by_default = true,
  new_window_buffer = 'single',
  quickterm_direction = 'botright',
  quickterm_orientation = 'vertical',
  -- Use 'g' for global quickterm
  quickterm_scope = 't',
  quickterm_size = '80',
}

-- Nvimux custom bindings
nvimux.bindings.bind_all{
  {'s', ':NvimuxHorizontalSplit', {'n', 'v', 'i', 't'}},
  {'v', ':NvimuxVerticalSplit', {'n', 'v', 'i', 't'}},
}
EOF
```
opening a new split using either `s` or `v` opens a empty split and not a terminal.

**Comment by hkupty** [comment]
Hi! Thanks for the interest in nvimux and the issue.

`open_term_by_default` works only for new tabs, wich isn't ideal. You can circumvent that by appending ` | term` to your maps.

I'll be on vacations until dec 1st and I'll come up with a decent solution for this.

Cheers,
Henry

**Comment by hkupty** [comment]
I fixed this with a different approach.

Instead of an `open_term_by_default`, a setting for `new_window` allows you to use `term` or whatever you feel better. Defaults to `enew`, so it ensures a new bufffer.

Also, settings can be changed by using `:NvimuxSet new_window term`, which causes the config to hot reload.

Cheers,
Henry
