### ISSUE TITLE
<C-b>[ does nothing

### ISSUE THREAD

**Issue by meepcode** [hkupty/nvimux#6]
I commonly use \<C-b>[ in tmux to view large bodies of text outputted by a command.  However I seem to notice that using \<C-b>[ does nothing.

**Comment by hkupty** [comment]
It's supposed to leave insert mode on terminal buffers, so you can navigate around.
Isn't it working?

**Comment by hkupty** [comment]
I'm closing this issue. If you think `<C-b>[`should do something more or can be enhanced, feel free to reopen it.
