### ISSUE TITLE
<c-b> ! functionality

### ISSUE THREAD

**Issue by ds26gte** [hkupty/nvimux#7]
In tmux, `<c-b> !` breaks the current pane (unless it's already the only pane in its current window) into a new window of its own. Is it possible to get this in nvimux?

**Comment by hkupty** [comment]
Sure! Actually, this is already solved in the lua branch. I'll backport
this to master asap.

Cheers,

**Comment by hkupty** [comment]
Sorry for taking long to fix this. Hope this is correct now.

Cheers!
